### ISSUE TITLE
License this project under the BSD License

### ISSUE THREAD

**Issue by Spitfire1900** [Jurrie/jsch-111-bugfix#1]
This bugfix is unable to be accepted by the JSch project because its license is incompatible with JSch's BSD License.

http://www.jcraft.com/jsch/LICENSE.txt

**Comment by Jurrie** [comment]
Thanks for your feedback. I actually don't care all that much about the license, so I changed it in commit 1da6da4d30a123c4ae0bfd0e78f2abed5efdded7 to the 3-clause BSD license that JSch uses. I released version 2.0.0 (no changes except the license) - should be in the public repositories soon.
